### ISSUE TITLE
JsonACE 1.4.1 Beautify doesn't work

### ISSUE THREAD

**Issue by visualight** [acrogenesis/JSONAce#2]
Hello,

Thank you for the new feature (raw - beautify) button for JsonACE.
I have a problem: when I click on the RAW button and then (after) I click the button Beautify, I have a blank page (i must refresh the page). Here is a json demo : http://json.org/example. I use the latest version of Safari (Yosemite).

Another thing: when you switch to RAW mode, it would be good to prevent the text (raw json) to pass below the button (we do not know to read). It would define a sort of padding or a fixed margin)

Is it possible?

thank you

**Comment by acrogenesis** [comment]
Gonna work on this, thanks for reporting

**Comment by acrogenesis** [comment]
@visualight I've just released v1.5. The json demo you gave me (http://json.org/example) was another but that page shouldn't be parsed as it has more content than just json so I fixed that.
I also fixed the problems where a blank page could be shown instead of the beautified version.
And I added an alpha to the button so you could see thru.

I'm gonna close this, but feel free to reopen it. :+1:
